clean:
  drop_null_threshold: 0.2
  drop_columns: ["default"]
select:
  keep_columns:  # para fijarlas explícitamente
    - age
    - job
    - marital
    - education
    - contact
    - month
    - day_of_week
    - campaign
    - previous
    - poutcome
    - emp.var.rate
    - cons.price.idx
    - cons.conf.idx
    - euribor3m
    - nr.employed
    - y
features:
  out_csv: data/interim/banking_features.csv
  derive_prev_contact_from_pdays: true
  pdays_never_value: 999
  drop_pdays_after_derive: true
  yes_no_to_binary_cols: ["housing", "loan", "default", "y"]
  report_summary: true
format:
  target_name: y
  positive_label: "yes"
  order_target_last: true
