clean:
  drop_null_threshold: 0.2
  drop_columns: ["default"]
select:
  keep_columns:  # para fijarlas explícitamente
    - age
    - job
    - marital
    - education
    - contact
    - month
    - day_of_week
    - campaign
    - previous
    - poutcome
    - emp.var.rate
    - cons.price.idx
    - cons.conf.idx
    - euribor3m
    - nr.employed
    - y
features:
  out_csv: data/interim/banking_features.csv
  derive_prev_contact_from_pdays: true
  pdays_never_value: 999
  drop_pdays_after_derive: true
  yes_no_to_binary_cols: ["housing", "loan", "default", "y"]
  report_summary: true
format:
  target_name: y
  positive_label: "yes"
  order_target_last: true
experiment:
  input_path: data/processed/bank_formatted.csv
  target_name: y
  test_size: 0.2
  cv_folds: 5
  random_state: 1
  balancing_method: undersampling
  tracking_uri: "file:./mlruns"
  experiment_name: "Proyecto 13MBID-ABR2526 - Experimentación"

train:
  input_csv: data/processed/bank_formatted.csv
  target_col: y
  test_size: 0.2
  random_state: 42
  balancing_method: undersample   

  model:
    name: KNN                     
    knn:
      n_neighbors: 5
      weights: uniform         
      n_jobs: -1
    decision_tree:
      max_depth: null
      min_samples_leaf: 1
    random_forest:
      n_estimators: 200
      n_jobs: -1
    logistic_regression:
      max_iter: 200
      solver: liblinear
    linear_svc:
      C: 1.0
